### ISSUE TITLE
Ugly registration dialog

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Clock-of-Change-Frontend#7]
On the current `master` dd176b3b0443f267783bfbacc90111834a64f5d2
1. when I start the frontend and the backend with `docker-compose up --build`
2. open another terminal and run `docker-compose run --rm cli wp-init.sh`
3. visit [Page 5](http://localhost:8000/wp-admin/post.php?post=5) and click on "preview"
4. open the registration dialog

I see this:
![Screenshot (35)](https://user-images.githubusercontent.com/2110676/54059164-76108600-41f8-11e9-809b-155829edb4ff.png)

My browser:
```sh
$ chromium --version
Chromium 72.0.3626.121 Arch Linux
```

**Comment by matthib** [comment]
Seems like we are using the [Avada Theme](https://avada.theme-fusion.com/) on the live version of the Clock of Change as our Wordpress theme: https://human-connection.org/uhr-des-wandels/
The Clock of Change Frontend seems to rely on the styles and icons of the Avada theme. In order to have the same result in the development environment, we need the Avada theme in the Wordpress Docker container as well.
